services:
  crmdb:
    image: mongo:5.0.0
    container_name: crm_database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    networks:
      - crm_network

networks:
  crm_network:
    driver: bridge